version: '3.5'
networks:
  the_continental:
    name: the_continental

services:
  mongodb:
    image : mongo:4.4.6
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /etc/timezone:/etc/timezone:rw
      - /etc/localtime:/etc/localtime:rw
    ports:
    - 27017:27017
    restart: unless-stopped
    networks:
      - the_continental

  backend:
    image : thecontinentalbackend
    container_name: thecontinentalbackend
    build:
      context: ./
      dockerfile: backend.dockerfile
    working_dir: /var/www
    volumes:
      - /etc/timezone:/etc/timezone:rw
      - /etc/localtime:/etc/localtime:rw
      # - ./backend/:/var/www
    ports:
      - 3100:3100
      - 4000:4000 
    networks:
      - the_continental

  frontend:
    image : thecontinentalfrontend
    container_name: thecontinentalfrontend
    build:
      context: ./
      dockerfile: frontend.dockerfile
    working_dir: /var/www
    volumes:
      - /etc/timezone:/etc/timezone:rw
      - /etc/localtime:/etc/localtime:rw
      # - ./frontend/:/var/www
    ports:
      - 9000:9000
    networks:
      - the_continental

  nginx:
    image : nginx
    container_name: nginx-server
    depends_on:
      - frontend
      - backend
    restart: always
    build:
      context: ./
      dockerfile: nginx.dockerfile
    ports:
      - 3050:80
    networks:
      - the_continental